### ISSUE TITLE
TensorFlowLiteTaskText requires outdated GoogleToolboxForMac

### ISSUE THREAD

**Issue by tinder-owenthomas** [tensorflow/tflite-support#404] opened 2021-03-25 20:11 UTC
Currently the Cocoapods podspec for `TensorFlowLiteTaskText` has a dependency on Google Toolbox with an explicit version (`'GoogleToolboxForMac', '2.2.1'`). This is no longer the latest version of the Toolbox though which is starting to cause conflicts with other Pods. Any chance the podspec could be updated to use major version pinning so it can adjust as Google releases new minor and patch releases (i.e. `'GoogleToolboxForMac', '~> 2.0'`)?

**Comment by wangtz** [comment] 2021-03-29 10:14
Sound reasonable to me. 

Any thoughts @yyoon ?

Thanks,
Tiezhen

**Comment by yyoon** [comment] 2021-03-30 00:06
Sounds good to me.

@lu-wang-g @xunkai55 Should we push a new version with this change?

**Comment by lu-wang-g** [comment] 2021-03-30 00:51
A new version will be great! As we are soon releasing TFLite Support 2.5 on the Java side, so it will be great to push for a new Cocoapods version. @xunkai55 is the Cocoapods release under your plan?

Also, is it possible to pin to the major version as suggested?

**Comment by yyoon** [comment] 2021-03-30 01:42
> A new version will be great! As we are soon releasing TFLite Support 2.5 on the Java side, so it will be great to push for a new Cocoapods version. @xunkai55 is the Cocoapods release under your plan?

I think we should rather publish 0.1.1 ASAP with only the dependency constraint change from 0.1.0. This should unblock any users having the same issues right now. I can proceed with that if you're okay with it.

> Also, is it possible to pin to the major version as suggested?

Yes, that's well supported by CocoaPods, as suggested by @tinder-owenthomas. I'd prefer we specify `~> 2.2.1` as we haven't really tested it between `[2.0.0, 2.2.1)`.

**Comment by lu-wang-g** [comment] 2021-03-30 01:47
@yyoon sounds good! Actually, it's not TFLite Support 2.5; it's TFLite Support 0.2, which depends on TFLite 2.5. But anyway, 0.1.1 sounds good to me. Thanks a lot!

**Comment by yyoon** [comment] 2021-03-30 06:31
@tinder-owenthomas I've just published `TensorFlowLiteTaskText` pod version `0.1.1` with the modified dependency constraint.

I'm closing this for now, but please feel free to reopen if the issue hasn't been properly resolved.

**Comment by tinder-owenthomas** [comment] 2021-03-30 18:12
Thanks for looking into this @yyoon! 

It looks like right now it is pinned at `~> 2.2.1` which will allow for patch updates, but only as far as 2.2.2 (as that's the last 2.2 patch they issued). Any chance we can pin at `~> 2.2` without the patch specifier to allow any 2.x.x version? Google is up to 2.3.1 now which is what our other dependencies are looking for, and will presumably bump to 2.4.x in the near future - but assuming they are following proper semantic versioning there will not be breaking changes until they go to a new 3.x.x major version so any 2.x.x should be ok.

**Comment by yyoon** [comment] 2021-04-01 02:31
Oh, somehow I didn't realize CocoaPods would lock the minor version as well when specifying the patch.
Yeah, the intended behavior is the one you described with `~> 2.2`. I'll try updating this again and let you know.

**Comment by yyoon** [comment] 2021-04-02 04:52
@tinder-owenthomas This should be fixed by now. Could you repo update and try again?

**Comment by tinder-owenthomas** [comment] 2021-04-15 23:34
Seems to be working. Thank you!

**Closed** 2021-04-15 23:34 UTC

**Comment by yyoon** [comment] 2021-04-15 23:47
Thanks for confirming!
