### ISSUE TITLE
Bazel run failed on nl_classifier_demo

### ISSUE THREAD

**Issue by SasukeFromTheHiddenLeaf** [tensorflow/tflite-support#395] opened 2021-03-22 07:40 UTC
Device Details:

**OS:**     Ubuntu 16.04.7 LTS
**Bazel:** 3.1.0
**GCC:**  gcc (Ubuntu 7.5.0-3ubuntu1~16.04) 7.5.0
**G++:**  g++ (Ubuntu 7.5.0-3ubuntu1~16.04) 7.5.0
**Python3:** 3.5.2
**Python:** 2.7.12

Command
`bazel-3.1.0 run -c opt  tensorflow_lite_support/examples/task/text/desktop:nl_classifier_demo --  --model_path=/tmp/movie_review.tflite  --text="What a waste of my time."  --input_tensor_name="input_text"  --output_score_tensor_name="probability" --sandbox_debug --verbose_failures`

I am trying to run TFLite Support Task Library on my laptop. I tried to run NLClassifier by referring to this [documentation](https://github.com/tensorflow/tflite-support/tree/master/tensorflow_lite_support/examples/task/text/desktop#nlclassifier), but I got the following error.

```
ERROR: /home/sasuke/tflite-support/tensorflow_lite_support/cc/task/text/nlclassifier/BUILD:12:1: C++ compilation of rule '//tensorflow_lite_support/cc/task/text/nlclassifier:nl_classifier' failed (Exit 1) gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 135 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
tensorflow_lite_support/cc/task/text/nlclassifier/nl_classifier.cc: In function 'tflite::support::StatusOr<std::unique_ptr<tflite::support::text::tokenizer::Tokenizer> > tflite::task::text::nlclassifier::{anonymous}::CreateRegexTokenizerFromProcessUnit(const tflite::ProcessUnit*, const tflite::metadata::ModelMetadataExtractor*)':
tensorflow_lite_support/cc/task/text/nlclassifier/nl_classifier.cc:136:10: error: could not convert 'regex_tokenizer' from 'std::unique_ptr<tflite::support::text::tokenizer::RegexTokenizer>' to 'tflite::support::StatusOr<std::unique_ptr<tflite::support::text::tokenizer::Tokenizer> >'
   return regex_tokenizer;
          ^~~~~~~~~~~~~~~
Target //tensorflow_lite_support/examples/task/text/desktop:nl_classifier_demo failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 171.710s, Critical Path: 41.22s
INFO: 326 processes: 326 linux-sandbox.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully

```

This error also described in [bazel build failed on nl_classifier_demo #211](https://github.com/tensorflow/tflite-support/issues/211). But he used a different command.

**Comment by lu-wang-g** [comment] 2021-03-23 19:29
I cannot reproduce this issue. Seems like it's due to different local bazel configurations. 

Does it help if you change the [method signature](https://github.com/tensorflow/tflite-support/blob/f80be3226744fa662c4fc8cdf6d256b639d7f88c/tensorflow_lite_support/cc/task/text/nlclassifier/nl_classifier.cc#L84) from 
```
StatusOr<std::unique_ptr<Tokenizer>> CreateRegexTokenizerFromProcessUnit(...)
```
to
```
StatusOr<std::unique_ptr< RegexTokenizer>> CreateRegexTokenizerFromProcessUnit(...)
```
?

**Comment by lu-wang-g** [comment] 2021-04-27 01:19
I'll close this issue for now. Feel free to let us know if you have further questions.

**Closed by lu-wang-g** 2021-04-27 01:19 UTC
